
/**
 * Battery Service Sample Application (GATT Server database)
 *
 **/
#include "wiced_bt_gatt.h"
#include "wiced_bt_cfg.h"
#include "gatt_server_db.h"
#include "wiced_bt_uuid.h"

/* GATT database */
const uint8_t gatt_db[] =
{
    // Generic Attribute service
    PRIMARY_SERVICE_UUID16 (HANDLE_BS_GATT_SERVICE, UUID_SERVICE_GATT),

    // Generic Access service
    PRIMARY_SERVICE_UUID16 (HANDLE_BS_GAP_SERVICE, UUID_SERVICE_GAP),

    CHARACTERISTIC_UUID16 (HANDLE_BS_GAP_SERVICE_CHAR_DEV_NAME,
                           HANDLE_BS_GAP_SERVICE_CHAR_DEV_NAME_VAL,
                           UUID_CHARACTERISTIC_DEVICE_NAME,
                               LEGATTDB_CHAR_PROP_READ,
                               LEGATTDB_PERM_READABLE),

    CHARACTERISTIC_UUID16 (HANDLE_BS_GAP_SERVICE_CHAR_DEV_APPEARANCE,
                           HANDLE_BS_GAP_SERVICE_CHAR_DEV_APPEARANCE_VAL,
                           UUID_CHARACTERISTIC_APPEARANCE,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE),
    //AUTOMATION SERVICE SERVER
    PRIMARY_SERVICE_UUID16 (HANDLE_AUTOMATION_SERVICE ,UUID_SERVICE_HOME_AUTOMATION),


    //FAN CONTROL ON OR OFF

    CHARACTERISTIC_UUID16(HANDLE_AUTOMATION_SERVICE_CHAR_FAN_CONTROL,
                     HANDLE_AUTOMATION_SERVICE_CHAR_FAN_CONTROL_VAL,
                                    UUID_CHARACTERISTIC_FAN_CONTROL,
                 LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE ,
                  LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ |LEGATTDB_CHAR_PROP_INDICATE),


    CHAR_DESCRIPTOR_UUID16_WRITABLE( HANDLE_AUTOMATION_SERVICE_FAN_CONTROL_CHAR_CFG_DESC,
                                        UUID_DESCRIPTOR_SERVER_CHARACTERISTIC_CONFIGURATION,
    LEGATTDB_PERM_AUTH_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE | LEGATTDB_PERM_AUTH_READABLE),


    //LIGHT CONTROLL ON OOR OFF
    CHARACTERISTIC_UUID16(HANDLE_AUTOMATION_SERVICE_CHAR_LIGHT_CONTROL,
                      HANDLE_AUTOMATION_SERVICE_CHAR_LIGHT_CONTROL_VAL,
                                      UUID_CHARACTERISTIC_BULB_CONTROL,
                    LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE ,
                     LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_CHAR_PROP_INDICATE),

    CHAR_DESCRIPTOR_UUID16_WRITABLE( HANDLE_AUTOMATION_SERVICE_LIGHT_CONTROL_CHAR_CFG_DESC,
                                        UUID_DESCRIPTOR_SERVER_CHARACTERISTIC_CONFIGURATION,
      LEGATTDB_PERM_AUTH_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE | LEGATTDB_PERM_AUTH_READABLE),


      //LIGHT BRIGHTNESS CONTROL
      CHARACTERISTIC_UUID16(HANDLE_AUTOMATION_SERVICE_CHAR_LIGHT_BRIGHTNESS_CONTROL,
                           HANDLE_AUTOMATION_SERVICE_CHAR_LIGHT_BRIGHTNESS_CONTROL_VAL,
                                           UUID_CHARACTERISTIC_BULB_BRIGHTNESS_CONTROL,
                         LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE,
                          LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_CHAR_PROP_INDICATE),

         CHAR_DESCRIPTOR_UUID16_WRITABLE( HANDLE_AUTOMATION_SERVICE_LIGHT_BRIGHTNESS_CONTROL_CHAR_CFG_DESC,
                                            UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
           LEGATTDB_PERM_AUTH_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE | LEGATTDB_PERM_AUTH_READABLE),

           //FAN SPEEED CONTROL
           CHARACTERISTIC_UUID16(HANDLE_AUTOMATION_SERVICE_CHAR_FAN_SPEED_CONTROL,
                   HANDLE_AUTOMATION_SERVICE_CHAR_FAN_SPEED_CONTROL_VAL,
                                     UUID_CHARACTERISTIC_FAN_SPEED_CONTROL,
                                   LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE,
                                    LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ |LEGATTDB_CHAR_PROP_INDICATE ),

                   CHAR_DESCRIPTOR_UUID16_WRITABLE( HANDLE_AUTOMATION_SERVICE_FAN_SPEED_CONTROL_CHAR_CFG_DESC,
                                                      UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                     LEGATTDB_PERM_AUTH_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE | LEGATTDB_PERM_AUTH_READABLE| LEGATTDB_PERM_READABLE),



};
const uint16_t gatt_db_size = sizeof(gatt_db);
